[package]
edition   = "2021"
name      = "atrl_native_launcher"
version   = "0.1.0"
workspace = "../.."

[dependencies]
away_team = { package = "away_team", path = "../.." }

bevy  = { workspace = true }
image = { workspace = true }
winit = { workspace = true }
